version: "3.9"

services:
  University:
    image: mysql
    ports:
      - 5432:5432
    environment:
      - MISQL_PASSCODE
      - MYSQL_DB
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app:ro
    environment:
      - NODE_ENV=docker
